### ISSUE TITLE
Implement LogManager

### ISSUE THREAD

**Issue by jovany-wang** [purecpp-org/raftcpp#162]
- [x] Basic log manager processes. #144
- [x] RequestAppendLogs RPC -> PullLogs RPC #144
- [ ] Use map to store logs. #144
- [ ] Unit tests to cover log managers: Like use 2 log managers as a test.
- [ ] CommitLogToStateMachine
- [ ] HandleReceivedLogsFromLeader
- [ ] TriggerAsyncDumpLogs
- [ ] Full IT cases

**Comment by jovany-wang** [comment]
It's invalid now because of the new arch refactor these days.
